# Generated by Django 3.2.6 on 2021-09-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramsList',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('onum', models.CharField(db_column='ONumber', max_length=255, verbose_name='ONumber')),
                ('model_num', models.CharField(db_column='ModelNum', max_length=255, null=True, verbose_name='ModelNum')),
                ('parts_name', models.CharField(db_column='PartsName', max_length=255, null=True, verbose_name='PartsName')),
                ('goods_name', models.CharField(db_column='GoodsName', max_length=255, null=True, verbose_name='GoodsName')),
                ('files_name', models.CharField(db_column='FilesName', max_length=255, null=True, verbose_name='FilesName')),
                ('item_code', models.CharField(db_column='ItemCode', max_length=255, null=True, verbose_name='ItemCode')),
                ('tools', models.IntegerField(db_column='Tools', null=True, verbose_name='FilesName')),
                ('creator', models.CharField(db_column='Creator', max_length=255, null=True, verbose_name='Creator')),
                ('tooling', models.CharField(db_column='Tooling', max_length=255, null=True, verbose_name='Tooling')),
                ('folder_path', models.CharField(db_column='FolderPath', max_length=255, null=True, verbose_name='FolderPath')),
                ('create_date', models.CharField(db_column='CreateDate', max_length=50, null=True, verbose_name='CreateDate')),
                ('process_time', models.CharField(db_column='ProcessTime', max_length=50, null=True, verbose_name='ProcessTime')),
            ],
            options={
                'db_table': 'Programs_list',
            },
        ),
        migrations.CreateModel(
            name='ToolingsList',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('onum', models.CharField(db_column='ONumber', max_length=255, verbose_name='ONumber')),
                ('item_code', models.CharField(db_column='ItemCode', max_length=255, null=True, verbose_name='ItemCode')),
                ('files_name', models.CharField(db_column='FilesName', max_length=255, null=True, verbose_name='FilesName')),
                ('create_date', models.CharField(db_column='CreateDate', max_length=50, null=True, verbose_name='CreateDate')),
                ('tooling', models.CharField(db_column='Tooling', max_length=255, null=True, verbose_name='Tooling')),
                ('folder_path', models.CharField(db_column='FolderPath', max_length=255, null=True, verbose_name='FolderPath')),
                ('tnum', models.CharField(db_column='TNumber', max_length=255, null=True, verbose_name='TNumber')),
                ('tool_name', models.CharField(db_column='ToolName', max_length=255, null=True, verbose_name='ToolName')),
                ('holder_name', models.CharField(db_column='HolderName', max_length=255, null=True, verbose_name='HolderName')),
                ('cut_distance', models.DecimalField(db_column='CutDistance', decimal_places=3, max_digits=8, null=True, verbose_name='CutDistance')),
                ('program', models.ForeignKey(db_column='ProgramID', on_delete=django.db.models.deletion.CASCADE, related_name='toolings', to='program.programslist', verbose_name='Program')),
            ],
            options={
                'db_table': 'Toolings_list',
            },
        ),
    ]
