# Generated by Django 3.2.7 on 2021-09-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolingslist',
            name='tnum',
            field=models.IntegerField(db_column='TNumber', default=0, verbose_name='TNumber'),
        ),
    ]
