# Generated by Django 3.2.7 on 2021-10-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_toolingslist_tnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolingslist',
            name='cut_distance',
            field=models.DecimalField(db_column='CutDistance', decimal_places=3, max_digits=15, null=True, verbose_name='CutDistance'),
        ),
    ]
