# Generated by Django 3.2.7 on 2021-11-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_alter_toolingslist_cut_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='programslist',
            name='comment1',
            field=models.CharField(db_column='Comment1', max_length=255, null=True, verbose_name='Comment1'),
        ),
        migrations.AddField(
            model_name='programslist',
            name='comment2',
            field=models.CharField(db_column='Comment2', max_length=255, null=True, verbose_name='Comment2'),
        ),
        migrations.AddField(
            model_name='programslist',
            name='size',
            field=models.CharField(db_column='Size', max_length=255, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='toolingslist',
            name='tip_name',
            field=models.CharField(db_column='TipName', max_length=255, null=True, verbose_name='TipName'),
        ),
    ]
