# Generated by Django 3.2.7 on 2021-11-23 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('program', '0005_nonepermanent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCheckHistory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='CheckNo', default=1, verbose_name='No')),
                ('tooling', models.CharField(db_column='Tooling', max_length=255, null=True, verbose_name='Tooling')),
                ('tnum', models.IntegerField(db_column='TNumber', default=0, verbose_name='TNumber')),
                ('tool_name', models.CharField(db_column='ToolName', max_length=255, null=True, verbose_name='ToolName')),
                ('holder_name', models.CharField(db_column='HolderName', max_length=255, null=True, verbose_name='HolderName')),
                ('tip_name', models.CharField(db_column='TipName', max_length=255, null=True, verbose_name='TipName')),
                ('started_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='tool_histories', to='user.user', verbose_name='User')),
            ],
            options={
                'db_table': 'Tool_Check_History',
            },
        ),
    ]
