# Generated by Django 3.2.7 on 2021-11-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_toolcheckhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolcheckhistory',
            name='holder_name',
        ),
        migrations.RemoveField(
            model_name='toolcheckhistory',
            name='tip_name',
        ),
        migrations.RemoveField(
            model_name='toolcheckhistory',
            name='tnum',
        ),
        migrations.RemoveField(
            model_name='toolcheckhistory',
            name='tool_name',
        ),
        migrations.AddField(
            model_name='toolcheckhistory',
            name='program_info',
            field=models.CharField(db_column='ONum String', max_length=255, null=True, verbose_name='ONum String'),
        ),
        migrations.CreateModel(
            name='ToolCheckDetail',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('tooling', models.CharField(db_column='Tooling', max_length=255, null=True, verbose_name='Tooling')),
                ('tnum', models.IntegerField(db_column='TNumber', default=0, verbose_name='TNumber')),
                ('tool_name', models.CharField(db_column='ToolName', max_length=255, null=True, verbose_name='ToolName')),
                ('holder_name', models.CharField(db_column='HolderName', max_length=255, null=True, verbose_name='HolderName')),
                ('tip_name', models.CharField(db_column='TipName', max_length=255, null=True, verbose_name='TipName')),
                ('exchange', models.BooleanField(db_column='Exchange', default=False, verbose_name='Exchange')),
                ('correction', models.BooleanField(db_column='Correction', default=False, verbose_name='Correction')),
                ('history', models.ForeignKey(db_column='HistoryID', on_delete=django.db.models.deletion.CASCADE, related_name='history_details', to='program.toolcheckhistory', verbose_name='HistoryDetails')),
            ],
        ),
    ]
