# Generated by Django 3.2.7 on 2021-11-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_auto_20211123_1516'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='toolcheckdetail',
            table='Tool_Check_Detail',
        ),
    ]
