# Generated by Django 3.2.7 on 2021-11-23 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_alter_toolcheckdetail_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcheckhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='EndedAt', default=django.utils.timezone.now, verbose_name='EndedAt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toolcheckhistory',
            name='started_at',
            field=models.DateTimeField(db_column='StartedAt', null=True, verbose_name='StartedAt'),
        ),
    ]
