# Generated by Django 3.2.7 on 2021-11-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20211123_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolcheckdetail',
            name='holder_name',
            field=models.CharField(blank=True, db_column='HolderName', max_length=255, null=True, verbose_name='HolderName'),
        ),
        migrations.AlterField(
            model_name='toolcheckdetail',
            name='tip_name',
            field=models.CharField(blank=True, db_column='TipName', max_length=255, null=True, verbose_name='TipName'),
        ),
        migrations.AlterField(
            model_name='toolcheckdetail',
            name='tool_name',
            field=models.CharField(blank=True, db_column='ToolName', max_length=255, null=True, verbose_name='ToolName'),
        ),
        migrations.AlterField(
            model_name='toolcheckdetail',
            name='tooling',
            field=models.CharField(blank=True, db_column='Tooling', max_length=255, null=True, verbose_name='Tooling'),
        ),
    ]
