# Generated by Django 3.2.13 on 2022-05-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('aufnr', models.CharField(db_column='AUFNR', max_length=12, primary_key=True, serialize=False, verbose_name='AUFNR')),
                ('matnr', models.CharField(db_column='MATNR', max_length=18, null=True, verbose_name='MATNR')),
                ('dwerk', models.CharField(db_column='DWERK', max_length=4, null=True, verbose_name='DWERK')),
            ],
            options={
                'db_table': 'SAP_PPT_FL_AFPO',
            },
        ),
    ]
