# Generated by Django 3.2.6 on 2021-09-04 14:27

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='UserID', max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='従業員番号')),
                ('name', models.CharField(db_column='UserName', max_length=100, null=True, verbose_name='名前')),
                ('avatar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], db_column='Avatar', force_format=None, keep_meta=True, null=True, quality=75, size=[500, 500], upload_to=user.models.user_directory_path, verbose_name='アバター')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_column='Token', max_length=50, verbose_name='キー')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt', verbose_name='作成日時')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='user.user', verbose_name='ユーザー')),
            ],
        ),
    ]
